name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          cache: true

      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - run: ls -lah

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dynport-server
          fail_on_unmatched_files: true

      - uses: MCJack123/ghaction-generate-release-hashes@v3
        with:
          hash-type: sha256
          file-name:  SHASUM256.txt

      - uses: actions/upload-artifact@v2
        with:
          name: Asset Hashes
          path: SHASUM256.txt
