name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install dependencies
        run: go get .

      - name: Build
        run: CGO_ENABLED=0 go build

      - name: Checksum
        run: sha256sum dynport-server > SHASUM256.txt

      - name: Test
        run: go test -v ./...

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dynport-server
            SHASUM256.txt
          fail_on_unmatched_files: true
